### ISSUE TITLE
nitro:q looks wrong.

### ISSUE THREAD

**Issue by dhull** [synrc/nitro#22]
For `nitro:q` you have

https://github.com/synrc/nitro/blob/14c7caea5c5f7289b8c4c8b1b1f04835e568da40/src/nitro.erl#L8-L10

I suspect what you want is:
```erlang
q(Key) -> get(Key, []).
q(Key, Default) ->
  case get(Key) of
    undefined -> Default;
    Value     -> Value
  end.
```

**Comment by 5HT** [comment]
If q/2 is not public then it's ok, but I understand your point.
Also I assume you mean:
```
q(Key) -> q(Key, []).
```
