### ISSUE TITLE
Get/Set Browser Cookies

### ISSUE THREAD

**Issue by etxemag75** [synrc/nitro#24]
Unless I missed something in N2O/NITRO, I need a interface or way to Get/Set Browser Cookies, so requesting it:
`nitro:cookie(Key) -> Binary`
`nitro:cookie(Key, Value, Path, MinutesToLive) `

I tried to work around this, it is possible to set browser cookie like this:
`nitro:wire(nitro:f("document.cookie=\"~s=~s\"",["user","Joe"])),`

But unable to read cookies since it seems #api erlang callback does not work:
`nitro:wire(#api{name ="getCookies",delegate=index}),`

But browser console reports: 

> SyntaxError: Unexpected identifier 'getCookies'

Otherwise I could maybe have retrieved it by this in erlang callback `nitro:wire(<<"document.getCookies('document.cookie');">>),`

**Comment by 5HT** [comment]
We removed cookies from N2O since 5.11, but added into NITRO 4.7.3 the following API:

```elixir
iex(1)> :nitro.cookie 'hello', 'world'
[]
iex(2)> :erlang.get :actions
[
  {:wire, :action, [], [], :action_wire,
   'document.cookie=\'hello=world; path=/; expires=Sat, 26-Jul-2087 00:56:15 GMT\';',
   []}
]
```

you can use in inside your pages. The full example here: https://github.com/enterprizing/plm/commit/e262877e1e1148c2d8f5ce6e8d4d08cf1fa35eb6

```elixir
defmodule PLM.Login do
  use N2O, with: [:n2o, :nitro]
  use FORM
  require Logger
  def event(:init) do
    NITRO.clear(:stand)
    NITRO.cookie 'hello', 'world'
    NITRO.wire(api(name: 'getCookies', delegate: PLM.Login))
    mod = PLM.Forms.Pass
    NITRO.insert_bottom(:stand, FORM.new(mod.new(mod, mod.id()), mod.id()))
  end
  def event({:SMS, _}), do: NITRO.wire("document.getCookies('sample string');")
  def event(any), do: IO.inspect any
  def api_event(_,_,_), do: IO.inspect "API EVENT~n"
end
```

**Comment by 5HT** [comment]
Maybe it's time to move `n2o_nitro` to NITRO as well. Let me know what do you think!

**Comment by etxemag75** [comment]
I pulled latest NITRO/N2O and tested your added interfaces, nitro:cookie/2 and cookie/3, seems to work fine! (thanks for adding) Thx also for fixing #api callback issue!

For completeness, would be good if you could add this function to get a certain cookie also since they are already in the context.

```
cookies() -> cowboy_req:parse_cookies((get(context))#cx.req).
cookie(Key) -> case lists:keyfind(Key, 1, cowboy_req:parse_cookies((get(context))#cx.req)) of false -> undefined; {_, Value} -> Value end.
```
_Worth mentioning that the set cookie is not visible until next page reload._

Regarding moving n2o_nitro from N2O to NITRO, seems fine to me.

**Comment by 5HT** [comment]
> Worth mentioning that the set cookie is not visible until next page reload.

It was to be in sync with cookies ETS table in 5.11 I just removed this. We had server-side controlled cookies, that's why we had infinite expire time. If you want server controlled cookies we need an additional table not mix them with session variables n2o:session (sessions), nitro:cookie (cookies).

**Comment by etxemag75** [comment]
In my use cases, it is enough that they are visible after page reload, i.e. browser controlled cookies.

Would be nice if you could add to nitro.erl :

```
cookies() -> cowboy_req:parse_cookies((get(context))#cx.req).
cookie(Key) -> case lists:keyfind(Key, 1, cowboy_req:parse_cookies((get(context))#cx.req)) of false -> undefined; {_, Value} -> Value end.
```

You could close this ticket as solved anyway.

**Comment by 5HT** [comment]
It's added in 4.7.4 https://github.com/synrc/nitro/commit/eb3fe4b9588f07520a62bcaf5656d32d65b63859
