### ISSUE TITLE
Pickled messaged

### ISSUE THREAD

**Issue by umka1332** [synrc/nitro#44]
https://github.com/synrc/nitro/blob/master/man/nitro_n2o.htm#L68-L70
Those 3 lines contains 3 different names for message:
Pickle message - singular without 'ed'
Those messages - plural
Pickled messaged - singular with too many 'ed'.
Some normalization needed.

**Comment by 5HT** [comment]
PICKLE message sends to server prerendered (by server) encripted message.
       These messages hold #ev record with callee information (encripted).
       Such pickled messages can prolongate expiration field in session token (renewed)
       by updating client token on each UI request (tracking user activity) when
       n2o application variable
